In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

In [2]:
choco = pd.read_csv("../src/chocolate_sales.csv")

In [3]:
choco.head()

,Sales Person,Country,Product,Date,Amount,Boxes Shipped
0,Jehu Rudeforth,UK,Mint Chip Choco,04/01/2022,"$5,320.00",180
1,Van Tuxwell,India,85% Dark Bars,01/08/2022,"$7,896.00",94
2,Gigi Bohling,India,Peanut Butter Cubes,07/07/2022,"$4,501.00",91
3,Jan Morforth,Australia,Peanut Butter Cubes,27/04/2022,"$12,726.00",342
4,Jehu Rudeforth,UK,Peanut Butter Cubes,24/02/2022,"$13,685.00",184

In [4]:
choco.info()

<class 'pandas.DataFrame'>
RangeIndex: 3282 entries, 0 to 3281
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Sales Person   3282 non-null   str
 1   Country        3282 non-null   str
 2   Product        3282 non-null   str
 3   Date           3282 non-null   str
 4   Amount         3282 non-null   str
 5   Boxes Shipped  3282 non-null   int64
dtypes: int64(1), str(5)
memory usage: 154.0 KB

### data column transformation

In [8]:
choco['Amount'] = choco['Amount'].str.replace('$','')

In [9]:
choco.head()

,Sales Person,Country,Product,Date,Amount,Boxes Shipped
0,Jehu Rudeforth,UK,Mint Chip Choco,04/01/2022,"5,320.00",180
1,Van Tuxwell,India,85% Dark Bars,01/08/2022,"7,896.00",94
2,Gigi Bohling,India,Peanut Butter Cubes,07/07/2022,"4,501.00",91
3,Jan Morforth,Australia,Peanut Butter Cubes,27/04/2022,"12,726.00",342
4,Jehu Rudeforth,UK,Peanut Butter Cubes,24/02/2022,"13,685.00",184

In [10]:
choco['Amount'] = choco['Amount'].str.replace(',','')

In [11]:
choco.head()

,Sales Person,Country,Product,Date,Amount,Boxes Shipped
0,Jehu Rudeforth,UK,Mint Chip Choco,04/01/2022,5320.00,180
1,Van Tuxwell,India,85% Dark Bars,01/08/2022,7896.00,94
2,Gigi Bohling,India,Peanut Butter Cubes,07/07/2022,4501.00,91
3,Jan Morforth,Australia,Peanut Butter Cubes,27/04/2022,12726.00,342
4,Jehu Rudeforth,UK,Peanut Butter Cubes,24/02/2022,13685.00,184

In [12]:
choco['Amount'] = choco['Amount'].astype('float64')

In [13]:
choco.info()

<class 'pandas.DataFrame'>
RangeIndex: 3282 entries, 0 to 3281
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Sales Person   3282 non-null   str
 1   Country        3282 non-null   str
 2   Product        3282 non-null   str
 3   Date           3282 non-null   str
 4   Amount         3282 non-null   float64
 5   Boxes Shipped  3282 non-null   int64
dtypes: float64(1), int64(1), str(4)
memory usage: 154.0 KB

In [14]:
choco.describe(include='number')

             Amount  Boxes Shipped
count   3282.000000    3282.000000
mean    6030.338775     164.666971
std     4393.980200     124.024736
min        7.000000       1.000000
25%     2521.495000      71.000000
50%     5225.500000     137.000000
75%     8556.842500     232.000000
max    26170.950000     778.000000

In [15]:
choco.shape

(3282, 6)

In [16]:
choco.columns

Index(['Sales Person', 'Country', 'Product', 'Date', 'Amount',
       'Boxes Shipped'],
      dtype='str')

In [20]:
choco['Date'] = pd.to_datetime(choco['Date'],dayfirst=True)

In [21]:
choco.head()

,Sales Person,Country,Product,Date,Amount,Boxes Shipped
0,Jehu Rudeforth,UK,Mint Chip Choco,2022-01-04,5320.0,180
1,Van Tuxwell,India,85% Dark Bars,2022-08-01,7896.0,94
2,Gigi Bohling,India,Peanut Butter Cubes,2022-07-07,4501.0,91
3,Jan Morforth,Australia,Peanut Butter Cubes,2022-04-27,12726.0,342
4,Jehu Rudeforth,UK,Peanut Butter Cubes,2022-02-24,13685.0,184

In [22]:
choco['Month'] = choco['Date'].dt.month
choco['Year'] = choco['Date'].dt.year

In [23]:
choco

,Sales Person,Country,Product,Date,Amount,Boxes Shipped,Month,Year
0,Jehu Rudeforth,UK,Mint Chip Choco,2022-01-04,5320.00,180,1,2022
1,Van Tuxwell,India,85% Dark Bars,2022-08-01,7896.00,94,8,2022
2,Gigi Bohling,India,Peanut Butter Cubes,2022-07-07,4501.00,91,7,2022
3,Jan Morforth,Australia,Peanut Butter Cubes,2022-04-27,12726.00,342,4,2022
4,Jehu Rudeforth,UK,Peanut Butter Cubes,2022-02-24,13685.00,184,2,2022
...,...,...,...,...,...,...,...,...
3277,Karlen McCaffrey,Australia,Spicy Special Slims,2024-05-17,5303.58,354,5,2024
3278,Jehu Rudeforth,USA,White Choc,2024-06-07,7339.32,121,6,2024
3279,Ches Bonnell,Canada,Organic Choco Syrup,2024-07-26,616.09,238,7,2024
3280,Dotty Strutley,India,Eclairs,2024-07-28,2504.62,397,7,2024
3281,Karlen McCaffrey,India,70% Dark Bites,2024-05-23,5915.87,355,5,2024

In [30]:
numerical_columns = []
categorical_columns = []

for col in choco.columns:
    if choco[col].dtype == 'O' or choco[col].dtype == 'string':
        categorical_columns.append(col)
    else:
        numerical_columns.append(col)

In [31]:
numerical_columns

['Date', 'Amount', 'Boxes Shipped', 'Month', 'Year']

In [32]:
categorical_columns

['Sales Person', 'Country', 'Product']